# Generated by Django 4.0.5 on 2022-07-10 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutosApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('mensaje', models.TextField()),
            ],
        ),
    ]
