# Generated by Django 4.0.5 on 2022-07-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutosApp', '0002_opinion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='apellido',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='mensaje',
            field=models.TextField(choices=[[0, 'muy malo'], [1, 'malo'], [2, 'bien'], [3, 'muy bien'], [4, 'excelente']]),
        ),
    ]
