# Generated by Django 4.0.5 on 2022-07-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutosApp', '0003_alter_opinion_apellido_alter_opinion_mensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='mensaje',
            field=models.TextField(),
        ),
    ]
