# Generated by Django 4.0.5 on 2022-07-14 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AutosApp', '0004_alter_opinion_mensaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null='((|rB|f|B|r|FR|rF|Rb|R|RB|U|Br|bR|rb|Rf|fr|b|br|BR|F|fR|rf|RF|Fr|u)\'\'\'|(|rB|f|B|r|FR|rF|Rb|R|RB|U|Br|bR|rb|Rf|fr|b|br|BR|F|fR|rf|RF|Fr|u)""")', upload_to='avatar/')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
