# Generated by Django 4.0.5 on 2022-07-25 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutosApp', '0006_alter_avatar_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(blank=True, null='((|u|Br|Fr|R|FR|rB|B|r|br|RB|bR|rF|fR|RF|f|b|rb|BR|Rf|fr|rf|U|Rb|F)\'\'\'|(|u|Br|Fr|R|FR|rB|B|r|br|RB|bR|rF|fR|RF|f|b|rb|BR|Rf|fr|rf|U|Rb|F)""")', upload_to='avatar/'),
        ),
    ]
