# Generated by Django 4.0.5 on 2022-07-25 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutosApp', '0007_alter_avatar_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(blank=True, null='((|rf|BR|Rf|F|Fr|Br|FR|fR|bR|f|RB|rF|RF|u|B|br|rb|Rb|b|U|rB|r|fr|R)\'\'\'|(|rf|BR|Rf|F|Fr|Br|FR|fR|bR|f|RB|rF|RF|u|B|br|rb|Rb|b|U|rB|r|fr|R)""")', upload_to='avatar/'),
        ),
    ]
