# Generated by Django 4.0.5 on 2022-07-25 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutosApp', '0008_alter_avatar_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(blank=True, null='((|bR|Br|Rf|br|RF|F|fR|Rb|r|rb|BR|rF|RB|f|rf|B|fr|FR|U|rB|u|R|Fr|b)\'\'\'|(|bR|Br|Rf|br|RF|F|fR|Rb|r|rb|BR|rF|RB|f|rf|B|fr|FR|U|rB|u|R|Fr|b)""")', upload_to='avatar/'),
        ),
    ]
