# Generated by Django 4.0.5 on 2022-07-30 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutosApp', '0009_alter_avatar_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(blank=True, null='((|bR|b|R|U|fR|BR|rb|f|RF|rf|Fr|FR|rF|rB|B|Rb|F|r|RB|br|Rf|u|Br|fr)\'\'\'|(|bR|b|R|U|fR|BR|rb|f|RF|rf|Fr|FR|rF|rB|B|Rb|F|r|RB|br|Rf|u|Br|fr)""")', upload_to='avatar/'),
        ),
    ]
