# Generated by Django 4.0.5 on 2022-07-30 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutosApp', '0010_alter_avatar_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(blank=True, null='((|rB|F|br|fr|RF|U|bR|b|R|RB|fR|FR|rF|Rb|B|Fr|BR|f|u|Br|Rf|r|rb|rf)\'\'\'|(|rB|F|br|fr|RF|U|bR|b|R|RB|fR|FR|rF|Rb|B|Fr|BR|f|u|Br|Rf|r|rb|rf)""")', upload_to='avatar/'),
        ),
    ]
