# Generated by Django 4.0.5 on 2022-07-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutosApp', '0011_alter_avatar_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(blank=True, null='((|Rf|rB|Fr|rF|Rb|bR|r|BR|F|B|fR|RB|U|R|rf|u|Br|fr|f|b|br|rb|FR|RF)\'\'\'|(|Rf|rB|Fr|rF|Rb|bR|r|BR|F|B|fR|RB|U|R|rf|u|Br|fr|f|b|br|rb|FR|RF)""")', upload_to='avatar/'),
        ),
    ]
